# Generated by Django 5.0.2 on 2024-03-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pergunta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='resolucao',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
